docs(readme): create a quick IT setup section while docs are outdated
bf2fc6cc711aee1a0c2a/cos-fleet-manager pull request #34
Opened 2022-02-14 20:25 UTC by rinaldodev

2022-02-14 20:31 UTC, rinaldodev commented
@valdar can you take a look?

2022-02-14 21:16 UTC, valdar requested changes
@rinaldodev great stuff! Can you pleas mention the PR needed to be added to the proper permission groups to have access to the vault?

2022-02-15 13:01 UTC, valdar approved these changes

2022-02-15 13:04 UTC, lburgazzoli approved these changes

2022-02-15 13:12 UTC, merged